#!/usr/bin/env bash

. $(dirname $0)/util
set -e

: ${PLATFORMS=}

platformFlag=""
if [ -n "$PLATFORMS" ]; then
  platformFlag="--platform=$PLATFORMS"
fi

if [ -n "$RUNC_PLATFORMS" ]; then
  buildxCmd build $cacheFromFlags $cacheToFlags \
    --target "binaries-linux-helper" \
    --platform "$RUNC_PLATFORMS" \
    $currentcontext
fi

buildxCmd build --secret id=ARTIFACTORY_APT_AUTH_CONF \
  --secret id=ARTIFACTORY_BASE64_GPG \
  $platformFlag $cacheFromFlags \
  $currentcontext
